### ISSUE TITLE
Security edge-case: unset join_rule is evaluated as invite, rather than private

### ISSUE THREAD

**Issue by TheArcaneBrony** [element-hq/synapse#16764]
## Description
---

Unset `join_rule` in `m.room.join_rules` is evaluated as ?????, causing it to be treated as `invite`, unlike when it's set to an unknown value, which would mean "no, you cant join no matter what")

## Steps to reproduce
---
- create room
- remove `join_rule` from state event
- use another account (on synapse! cant join from conduit due to failing an auth check, yet it will happily send a join event) to join
- get denied
- invite other account (synapse)
- accept invite
- you are now in room
- you are not supposed to be in room

## Homeserver
---

- feline.support, rory.gay (2020, unknown version)
- matrix.org, maunium.net, rory.gay (all ~1.95-ish i think? whatever is recent at this very moment)

### Installation methods

- feline.support: whatever the deploy thingy is
- matrix.org: how am i supposed to guess?
- maunium.net: no clue
- rory.gay: NixOS module

### Workers

- feline.support: i think so?
- matrix.org: probably
- maunium.net: no clue
- rory.gay: *no :)*

### Platform

- feline.support: no clue
- matrix.org: if i had to guess, some kind of linux i guess
- maunium.net: probably something that can run synapse, at least
- rory.gay: NixOS VM with 11 CPU threads, with 16GB of RAM, running on an AMD Epyc 7262.

### Configuration

I wont bother to include the other servers for this one...

- Experimental features: no
- Presence: yes
- Message retention: no
- Synapse modules: no

### Relevant log output
```log
none :)
```

### Anything else that would be useful to know?
```cs
false
```
```[tasklist]
### Tasks
- [ ] Fix bug
- [ ] Release
```

**Comment by erikjohnston** [comment]
> Unset `join_rule` in `m.room.join_rules` is evaluated as ?????, causing it to be treated as `invite`, unlike when it's set to an unknown value, which would mean "no, you cant join no matter what")

Unfortunately, this is a wart of the Matrix spec (as it affects the auth rules). This would require an MSC to change: https://github.com/matrix-org/matrix-spec-proposals/
