### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [element-hq/synapse#16773]
**Description:**

It would be nice if the project's code were moved to GitLab or Codeberg. GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by catfromplan9** [comment]
Mirrors might be useful, I suppose. I see no use case for moving entirely though. GitHub is a proprietary web service, yes, but I don't see why Microsoft would have a problem with this repository. Also, there's the hassle of getting contributors to make accounts on the new git service and learn how the UI works for submitting issues. If it were to have a mirror, an element team-hosted gitea instance would be what I suggest.

**Comment by progval** [comment]
Use case: issues were recently migrated from https://github.com/matrix-org/synapse to https://github.com/element-hq/synapse but because of limitations imposed by Github, timestamps and reacts cannot be preserved.

**Comment by erikjohnston** [comment]
Hi, thanks for the feedback. However, we are not going to move away from Github anytime soon due to the value we find in using it (and the ease in which people can contribute).

**Comment by catfromplan9** [comment]
Great to hear
