### ISSUE TITLE
The GitHub Pages (developer docs) CI workflow is failing on develop

### ISSUE THREAD

**Issue by anoadragon453** [element-hq/synapse#16804]
```
Extension error (autodoc2.sphinx.extension):
Handler <function run_autodoc at 0x7fed68b0fec0> for event 'builder-inited' threw an exception (exception: 'Attribute' object has no attribute 'repr_name')
```

Failing workflow: https://github.com/element-hq/synapse/actions/runs/7475715177/job/20344447295

Not sure why this would be failing now unless a version bump occurred recently.

**Comment by erikjohnston** [comment]
Do we actually ever use the generated documentation?

**Comment by anoadragon453** [comment]
I'm not actually sure where it is hosted, if anywhere.

**Comment by anoadragon453** [comment]
cc @reivilibre who originally wrote it and should have a say here I think.

**Comment by anoadragon453** [comment]
Unfortunately, this did cause the v1.99.0 documentation to fail to build during the release: https://github.com/element-hq/synapse/actions/runs/7542746086.

Presumably we can just merge the fix to the `release-v1.99` branch to re-deploy the documentation.

**Comment by anoadragon453** [comment]
I have found the developer docs: https://element-hq.github.io/synapse/dev-docs/develop/

They're pretty sparse at the moment, holding just a description of the federation sender. It also seems that they haven't built correctly since v1.95: https://github.com/element-hq/synapse/tree/gh-pages/dev-docs

I'll see whether I can fix the error, otherwise will opt for dropping it for now.

**Comment by reivilibre** [comment]
I'm not sure what would have changed here to break it, probably a dep bump.

I would like to keep it if possible, it'd be nice to start having more developer documentation. I have a couple of WIP bits I'd like to finish up and add someday as well.

**Comment by erikjohnston** [comment]
If we can easily fix this then I'm happy for us to do that, but I don't think we should either burn time on this or leave it broken.
