### ISSUE TITLE
Docker Docs Outdated: Permission denied on '.signing.key' 

### ISSUE THREAD

**Issue by kenodressel** [element-hq/synapse#16824]
### Description

When using the docker documentation to run new a matrix server on v1.99.0 it fails with `[Errno 13] Permission denied: '/data/localhost.signing.key'`

This is because of the changes in https://github.com/element-hq/synapse/commit/10ada2ff6d2a08108edf5b4dbe6562cc9465523d which adjusts the file permissions to 0640 instead of the previous 0644 which in itself is a great change but leaves this documentation broken. The docker container runs with a UID and GID of 991 but the generate steps run as root, therefore neither the group nor the user sufficiently overlaps with the generated files permissions.

The fix is to adjust the permissions of the volume / folder before generating the files and to use the right user when generating the files (eg. `-u 991:991`). Or another simple fix is to run `chown -R 991:991 ./your-data-dir` after the files have been generated.

This should be noted somewhere in the documentation.

### Steps to reproduce

1. 
```
docker run -it --rm \
    --mount type=volume,src=synapse-data,dst=/data \
    -e SYNAPSE_SERVER_NAME=my.matrix.host \
    -e SYNAPSE_REPORT_STATS=yes \
    matrixdotorg/synapse:latest generate
``` 
2.
```
docker run -d --name synapse \
    --mount type=volume,src=synapse-data,dst=/data \
    -p 8008:8008 \
    matrixdotorg/synapse:latest
```

### Homeserver

-

### Synapse Version

v1.99.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

SQLite

### Workers

Single process

### Platform

Arch

### Relevant log output

```shell
$ docker run -it --rm \
    --mount type=volume,src=synapse-data,dst=/data \
    -e SYNAPSE_SERVER_NAME=my.matrix.host \
    -e SYNAPSE_REPORT_STATS=yes \
    matrixdotorg/synapse:latest generate
Setting ownership on /data to 991:991
Creating log config /data/my.matrix.host.log.config
Generating config file /data/homeserver.yaml
Generating signing key file /data/my.matrix.host.signing.key
A config file has been generated in '/data/homeserver.yaml' for server name 'my.matrix.host'. Please review this file and customise it to your needs.

$ docker run --name synapse \ 
    --mount type=volume,src=synapse-data,dst=/data \
    -p 8008:8008 \
    matrixdotorg/synapse:latest
Starting synapse with args -m synapse.app.homeserver --config-path /data/homeserver.yaml

Error in configuration at 'signing_key':
  Error accessing file '/data/my.matrix.host.signing.key':
    [Errno 13] Permission denied: '/data/my.matrix.host.signing.key'

```

**Comment by lacafjh** [comment]
https://github.com/element-hq/synapse/issues/15202 also has the same issue and can be solved with the solution by [kenodressel](https://github.com/kenodressel), but the issue mentioned in https://github.com/element-hq/synapse/issues/13709 occurred after following the solution.

**Comment by 0KayKay** [comment]
Thank you a lot @kenodressel, this way I finally got my setup to run. It took me longer than I'm willing to admit :sweat_smile:

**Comment by fsackur** [comment]
Here's the relevant bit of code: https://github.com/element-hq/synapse/blob/v1.102.0rc1/docker/start.py#L202-L208

I got around this by passing `UID=0` and `GID=0` in the environment (running as root for now).

**Comment by alariej** [comment]
I've installed Synapse with Docker about 10 times, always without issue. And now I've just spent a day on this, thinking my VM setup was wrong :-( Fixed with `sudo chown -R 991:991 /var/lib/docker/volumes/synapse-data`. Thanks for the hint!

**Comment by aknyzsd** [comment]
how to fix  the bug with Docker on Windows(qwq)

**Comment by p9tnblwko** [comment]
> how to fix the bug with Docker on Windows(qwq)

docker compose down -v

and then:

docker run --rm -v matrix_synapse_data:/data alpine:latest sh -c "
mkdir -p /data
chown -R 991:991 /data
chmod -R 755 /data
echo 'Permissions set successfully'
"
