### ISSUE TITLE
Update MSC4028 implementation: Enable the unstable push rule by default

### ISSUE THREAD

**Issue by giomfo** [element-hq/synapse#16846]
Since [MSC4028](https://github.com/matrix-org/matrix-spec-proposals/pull/4028) has been implemented, I updated the spec about the unstable push rule with [this commit](https://github.com/matrix-org/matrix-spec-proposals/pull/4028/commits/49ace6d).

Indeed the unstable push rule `org.matrix.msc4028.encrypted_event` used during development should be **enabled** by default like the stable push rule.

This change has been triggered by a comment from the mobile dev team [here](https://github.com/element-hq/element-meta/issues/2065#issuecomment-1802170569). I realized that it was not risky to enabled this unstable push rule by default because we are using the experimental mode. Apply the same enabling value on the unstable and the stable push rules would make more relevant the current tests of this feature. See [here](https://github.com/element-hq/element-meta/issues/2065#issuecomment-1759918276) the current test plan.

I would add here a question for the Backend team: How the new push rule is handled when the MSC has successfully passed a merge FCP? I mean when the feature becomes stable.
Is the unstable push rule (stored in the existing account data) renamed/replaced automatically with the stable push rule?

**Comment by anoadragon453** [comment]
For context, the unstable `org.matrix.msc4028.encrypted_event` is included in every user's [default base append override rules](https://github.com/element-hq/synapse/blob/d4e3ad04cd722e3c98c85685d47a6d86029ffe0c/rust/src/push/base_rules.rs#L72-L276). However, the push rule will only be *evaluated* if the `experimental_features.` config option is set to `true`:

https://github.com/element-hq/synapse/blob/d4e3ad04cd722e3c98c85685d47a6d86029ffe0c/rust/src/push/mod.rs#L593-L597

> How the new push rule is handled when the MSC has successfully passed a merge FCP? I mean when the feature becomes stable.

Ideally we would just rename it in the codebase and provide a database migration to do the same for users automatically. This would result in push notifications being sent to mobile clients with the new rules immediately.

As for clients that compute push rules locally... do clients regularly pull down their push rules? If so, then we don't need to worry about telling clients proactively and can wait until they update themselves.

---

I apologise for such a slow response on this ticket. What would you currently like to see done about this issue? I see that the MSC hasn't moved forward much in the meantime, and is still not accepted.

**Comment by giomfo** [comment]
Thanks @anoadragon453 

>  What would you currently like to see done about this issue?

I'm requesting here to update the synapse implementation of MSC4028 in order to enable by default the unstable push rule org.matrix.msc4028.encrypted_event. By this way the synapse implementation will be aligned to my last MSC [update](https://github.com/matrix-org/matrix-spec-proposals/pull/4028/commits/49ace6d)

> I see that the MSC hasn't moved forward much in the meantime, and is still not accepted.

Yes, a plan was defined to move progressively on this MSC by enabling it progressively: https://github.com/matrix-org/internal-config/issues/1469. Unfortunately our efforts went on other topic.
**This is important to get this update at synapse level, to be aligned with the MSC.**
This MSC is the solution I promoted/promote internally to support mention_only notifications on mobile app. I think that the opportunity to work on/test it on EX will be back soon (when the EX team will have bandwidth)

**Comment by anoadragon453** [comment]
@giomfo generally we don't enable experimental features by default until they've been accepted into the Matrix spec. Doing so would enable it on `matrix.org` by default as well. I'm afraid still I don't understand why enabling the feature by default on all Synapse instances would make testing easier.

If you need the feature enabled by default on `beta.matrix.org`, we can do that. In addition, we're able to enable specific experimental features for specific users on `matrix.org` these days.

**Comment by giomfo** [comment]
@anoadragon453 I think you misunderstood my request. I'm asking here to enable the new push rule by default. I'm not asking to enable the feature itself. I agree that about the feature we should consider beta.matrix.org (this is the plan described [here](https://github.com/matrix-org/internal-config/issues/1469))

The mistake that I did when I wrote the MSC is to disable the unstable push rule by default (in its definition), which is not relevant and useless, because the unstable push rule is added as an experimental feature (when it is enabled). 

Hope this is clearer, ping me for a quick sync if not

**Comment by anoadragon453** [comment]
I see. So you would like to have the unstable push rule in client's push rules by default, even if the feature is disabled on the homeserver.

The homeserver would ignore the push rule and not process it if the feature is disabled, and clients that don't know what the unstable push rule means won't process it either.

I suppose that's fine, and I can whip up a PR with the appropriate logic.

**Comment by giomfo** [comment]
> I've just realised that by "enabling" the push rule, you may have been referring to setting the enabled flag on the push rule. So flipping [this line](https://github.com/element-hq/synapse/blob/422f3ecec1ffb4fa352f83d7ec8b3327f36a93c8/rust/src/push/base_rules.rs#L84) from false to true.

Yes, exactly 😄 

> Would you like to not filter the push rule even when the experimental feature is disabled?

I would prefer to follow the same behavior as the other experimental feature. My request is mainly to have the right `enabled` flag in the unstable push rule when we run some experimentations

**Comment by anoadragon453** [comment]
I've created a PR for this at https://github.com/element-hq/synapse/pull/17826

Please let me know if this does not satisfy the requirements.

**Comment by giomfo** [comment]
PR #17143 fixed my request 👍
