### ISSUE TITLE
Retract knocks when deactivating accounts

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/synapse#16861]
### Description

When deactivating a user, synapse goes through a cleanup process which includes steps to remove the user from the federation. This includes parting all joined rooms and rejecting pending invites:
https://github.com/element-hq/synapse/blob/232adfb95f9ec726c2c09f3329c098aa9060c1f7/synapse/handlers/deactivate_account.py#L167-L173

MSC2403 introduced knocking. Knocks similarly to invites linger until either retracted or approved/denied by another actor. Hence, similar to pending invites being shown in the room member list, knocks would usually also be shown to at least those room members with sufficient power level to manage them.

The synapse cleanup routine should also take care of pending knocks, setting them to leave instead.
This could be done by replacing the call to `get_rooms_for_user()` with a cloned one that does not only consider `JOIN` but also `KNOCK`
https://github.com/element-hq/synapse/blob/232adfb95f9ec726c2c09f3329c098aa9060c1f7/synapse/storage/databases/main/roommember.py#L690
or a new function similar to
https://github.com/element-hq/synapse/blob/232adfb95f9ec726c2c09f3329c098aa9060c1f7/synapse/handlers/deactivate_account.py#L197
but I could not find an existing method to list a user's pending knocks yet, so that would need to also be added.

### Steps to reproduce

- knock on a room
- deactivate user
- as the room admin, see the pending knock sticking around

### Homeserver

another

### Synapse Version

1.93

### Installation Method

Docker (matrixdotorg/synapse)

### Database

psql, single, not ported, probably yes

### Workers

Single process

### Platform

k8s rancher

### Configuration

- presence off
- retention off
- no modules

### Relevant log output

```shell
n/a
```

**Comment by clokep** [comment]
Sounds similar to matrix-org/synapse#16559.
