### ISSUE TITLE
3th person interrupting P2P video/audio call sends the ringtone to infinite loop 

### ISSUE THREAD

**Issue by pr0logas** [element-hq/synapse#16969]
### Description

If third person calls to another person which is currently talking with other teammate and the author clicks deny, dismiss button for third person (instead of answer) the Element will close the pop-up window however the ringing tone goes to bug state and rings forever. 
You need to kill Element program and start again to stop it.

We think this bug affects all Element software versions and has to do with UI button settings where the ringing tone shutdown has no event at all.

### Steps to reproduce

- Victoria calls John. John accepts the call;
- Peter now calls Victoria and interrupts Victoria's and John call;
- Victoria decides to deny a call with Peter (dismiss);
- Victoria's Element will ring the ringing tone forever. No matter what she click's now.

### Homeserver

private homeserver

### Synapse Version

{"server_version":"1.100.0"}

### Installation Method

Debian packages from packages.matrix.org

### Database

psql (PostgreSQL) 14.10 

### Workers

Single process

### Platform

Pretty much default config homeserver.yaml with Ubuntu 22.04 LTS

Coturn config:
```
listening-ip=xxx
allowed-peer-ip=xx
listening-port=3478
tls-listening-port=443
no-cli
min-port=49152
max-port=65535

verbose
log-file=/var/log/turn/coturn.log

# TLS
cert=/etc/zerossl/xxx/certificate.crt
pkey=/etc/zerossl/xxx/private.key

use-auth-secret
static-auth-secret=xxx
realm=xxx

no-multicast-peers
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.30.30.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=192.88.99.0-192.88.99.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
denied-peer-ip=240.0.0.0-255.255.255.255

total-quota=600
```

### Relevant log output

```shell
no-log-for-now
```

**Comment by reivilibre** [comment]
Sorry but I think this would be better reported in the Element repository for whichever version of Element you mean (web/Android/iOS?)

https://github.com/element-hq/element-web/issues

I don't really see how Synapse would be involved in this bug otherwise!
