### ISSUE TITLE
How to support mobile phone number login?

### ISSUE THREAD

**Issue by zoujiaqing** [element-hq/synapse#16967]
Apps such as Telegram allow users to login by mobile number.
How to make Matrix support mobile number login and registration?

**Comment by anoadragon453** [comment]
Synapse supports logging in with a phone number. You'll need to delegate the verification of phone numbers to a third-party service however. See the [`account_threepid_delegates`](https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#account_threepid_delegates) option.

Please use [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) for support requests.
