### ISSUE TITLE
Stickers don't appear

### ISSUE THREAD

**Issue by acexiis** [element-hq/synapse#16975]
When matrix.org isn't on the domain whitelist, it's impossible to load stickers. Anybody have an solution for that ?

Thanks

**Comment by acexiis** [comment]
Just for update: Stickers don't appear whether you don't authorize the federation with. matrix.org

**Comment by reivilibre** [comment]
Are these the default stickers that are built-in to Element? Probably they are already uploaded on a server somewhere and that one needs to be allowed in the federation.

**Comment by anoadragon453** [comment]
As with any media on a homeserver that you've blocked federation with, that media will be blocked as your homeserver is unable to download it.

As @reivilibre said, your options are to either add `matrix.org` to your domain whitelist, or to re-upload the stickers to your own homeserver, or one you can federate with.
