### ISSUE TITLE
Synapse sends empty `m.push_rules` account_data in initial sync

### ISSUE THREAD

**Issue by t3chguy** [element-hq/synapse#16987]
### Description

As per title. The spec lists a number of ordered default rules which must be present, and they are via the push rules API but missing in the corresponding account_data event.

![image](https://github.com/element-hq/synapse/assets/2403652/7f031149-55df-48a6-8612-064695c20365)

### Steps to reproduce

- inspect initial sync response

### Homeserver

matrix.org

### Synapse Version

1.102.0rc1

### Installation Method

I don't know

### Database

I don't know

### Workers

I don't know

### Platform

I don't know

### Configuration

I don't know

### Relevant log output

```shell
I don't know
```

### Anything else that would be useful to know?

`https://matrix-client.matrix.org/_matrix/client/v3/sync?filter=%7B%22room%22%3A%7B%22timeline%22%3A%7B%22unread_thread_notifications%22%3Atrue%2C%22limit%22%3A20%7D%2C%22state%22%3A%7B%22lazy_load_members%22%3Atrue%7D%7D%7D&timeout=0&_cacheBuster=1709907549083` for anyone wishing to sleuth logs `@webdevguru_github:matrix.org`

**Comment by erikjohnston** [comment]
The user in question has `m.push_rules` set to `{}` in `account_data` table. Somehow.

The easiest fix here would be to switch things around so the calculated push rules trump whatever is in account data:

https://github.com/element-hq/synapse/blob/892cbd0624acd1157803f8e88b7a491253053e18/synapse/handlers/sync.py#L1951-L1956

And/or make a background update to delete such entries from `account_data`.

We should also double check that there is no longer anyway of actually setting `m.push_rules` account data nowadays.

**Comment by erikjohnston** [comment]
> The easiest fix here would be to switch things around so the calculated push rules trump whatever is in account data

We actually used to do this, but the condition got swapped in https://github.com/matrix-org/synapse/pull/16325, so this is a regression from v1.93.0
