### ISSUE TITLE
DNS lookup failed: no results for hostname lookup

### ISSUE THREAD

**Issue by ne20002** [element-hq/synapse#16997]
I'm not sure if this is a bug or not.

I'm trying to set up my own ntfy server in the local network and Synapse complains about not being able to lookup the hostname even though it is working using curl in the container.

This is the log line:
`2024-03-16 12:58:54,612 - synapse.push.httppusher - 416 - WARNING - httppush.process-4 - Failed to push data to @stefan:****.ch/im.vector.app.android/https://ntfy.****.ch:8180/up3jGv5F9EzBJe?up=1: <class 'twisted.internet.error.DNSLookupError'> DNS lookup failed: no results for hostname lookup: ntfy.****.ch.
`

The ip to look up is the local ntfy server in my internal network. It is also added to the /etc/hosts in the container.

Setup: 

- using latest Synape (102) with official docker image
- havin my own ntfy server in my internal network with a certificate from my own CA
- copied my CA certificate to the synapse container
- my own CA certificate works as prooven by curl

So why is this not working?

**Comment by clokep** [comment]
Synapse by default won't connect to private IPs, you need to update your configuration to allow it. See https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#ip_range_whitelist

**Comment by ne20002** [comment]
Thank you. That fixed it. 

I now ran into the [next problem](https://github.com/element-hq/element-android/issues/8783). :(
