### ISSUE TITLE
[Documentation] Error in the user directory configuration description

### ISSUE THREAD

**Issue by giomfo** [element-hq/synapse#17016]
**Description:**

For my point of view there is a typo in the current description of the `search_all_users` parameter in [`config_documentation.md`](https://github.com/element-hq/synapse/blob/develop/docs/usage/configuration/config_documentation.md?plain=1#L3737C4-L3737C20).

This sentence: "_If set to true, will return all users who share a room with the user from the homeserver._" is not correct.

The right description for this value `true` is available in [`user_directory.md`](https://github.com/element-hq/synapse/blob/develop/docs/user_directory.md?plain=1#L70): "_if `search_all_users` is `true`, no such limits are placed and all users known to the server (matching the search query) will be returned._"

The following example helps to understand the meaning of _users known to the server_:
"Consider Alice, a user on server A, and Bob, a user on server B. Also consider that both servers have `search_all_users` set to true. Currently, Alice can only discover Bob (through the user directory) if server A is in a room that Bob is joined to."

**Comment by devonh** [comment]
I agree with your assessment.
See this PR for revised docs: https://github.com/element-hq/synapse/pull/17348
