### ISSUE TITLE
Declare support for Matrix v1.10

### ISSUE THREAD

**Issue by clokep** [element-hq/synapse#17021]
See https://github.com/matrix-org/synapse/issues/16709 for a previous version of this.

See [the changelog](https://spec.matrix.org/v1.10/changelog/#v110) (note that I stripped out spec clarifications).

----

### Client-Server API

- [ ] Allow `/versions` to optionally accept authentication, as per [MSC4026](https://github.com/matrix-org/matrix-spec-proposals/pull/4026).
- [x] Add local erasure requests, as per [MSC4025](https://github.com/matrix-org/matrix-spec-proposals/pull/4025).
  * This was essentially documenting what was implemented?
- [x] Use the `body` field as optional media caption, as per [MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
  * Client-only change.
- [ ] Add server support discovery endpoint, as per [MSC1929](https://github.com/matrix-org/matrix-spec-proposals/pull/1929).
- [x] Add support for multi-stream VoIP, as per [MSC3077](https://github.com/matrix-org/matrix-spec-proposals/pull/3077).
  * Client-only change.
- [x] Specify that the `Retry-After` header may be used to rate-limit a client, as per [MSC4041](https://github.com/matrix-org/matrix-spec-proposals/pull/4041).
  * #16947
- [x] Add support for recursion on the `GET /relations` endpoints, as per [MSC3981](https://github.com/matrix-org/matrix-spec-proposals/pull/3981).
  * #17023
-  [x] Clarify that the `m.push_rules` account data type cannot be set using the `/account_data` API, as per [MSC4010](https://github.com/matrix-org/matrix-spec-proposals/pull/4010).
   * #17022

**Comment by clokep** [comment]
@erikjohnston / @anoadragon453 I'd be curious on your thoughts on if Synapse could now declare v1.10 support:

* Auth for `/versions` *should* be accepted by Synape (but ignored) this seems inline with what the MSC proposes.
* Generally well-known endpoints aren't server by Synapse, and the server support endpoint isn't used by homeservers, so it is "supported".

🤷 Would be curious of opinions.

**Comment by anoadragon453** [comment]
>     * Auth for `/versions` _should_ be accepted by Synape (but ignored) this seems inline with what the MSC proposes.

I agree that we could call the current behaviour of Synapse, where it just ignores attempts at authenticating to `/versions`, "supporting" MSC4024.

>     * Generally well-known endpoints aren't server by Synapse, and the server support endpoint isn't used by homeservers, so it is "supported".

I agree that a "homeserver deployment" serving this endpoint via a separate webserver would thus constitute a full homeserver that supports Matrix v1.10. Synapse doesn't need to support serving this endpoint itself in order to declare support for v1.10.

I wouldn't be opposed to declaring v1.10 support before adding an option for Synapse to serve this endpoint itself.

**Comment by anoadragon453** [comment]
We discussed it briefly as the Element backend team and had no objections. So, go for it!
