### ISSUE TITLE
Redirect matrix-org github pages documentation ?

### ISSUE THREAD

**Issue by MatMaul** [element-hq/synapse#17020]
I just notice that I was looking at outdated documentation since I was still looking at the GH pages of the old repo:
https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html

It may deserve to have a big warning on top of the page pointing to https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html.

**Comment by dklimpel** [comment]
Related to:
- #16906

**Comment by MatMaul** [comment]
Indeed thanks I should have searched... Closing as duplicate.
