### ISSUE TITLE
Live messages

### ISSUE THREAD

**Issue by DonPrus** [element-hq/synapse#17030]
**Description:**
Sometimes there are situations when you describe a situation in real time, but you cannot send every piece of the message.

Or someone is in a hurry and can send a message one word at a time.

Proposal to take the basis of live messages from [SimpleX chat](https://simplex.chat/docs/guide/send-messages.html#sending-live-messages). When you send such a message, a bubble with your name appears, and the interlocutor sees the text directly while typing the message.

Messages are synchronized every few seconds or after writing a word.

**Comment by reivilibre** [comment]
This is a cool feature, but there's no reason that Synapse imposes why you couldn't do this today.

It would probably be better to take this suggestion to one of:

- a client's feature request tracker?
- a spec proposal? https://github.com/matrix-org/matrix-spec-proposals/

Synapse only gets the messages from A to B, it doesn't really care what they are and this is very possible today from Synapse's point of view, it just needs someone to write a client that does it :-)
