### ISSUE TITLE
Add Admin API endpoint to change one's nickname only in a room

### ISSUE THREAD

**Issue by Marc-Andrieu** [element-hq/synapse#17040]
**Description:**

Create an endpoint for the Admin API of Synapse, so that a server admin can change a user's nickname that is displayed _in a given room only_. (Or change the behavior of one which already exists)

**Motivation:**

In different spaces or channels, corresponding to different communities, one given user may play different roles. We may want to change automatically this user's nickname to match their role in each community (or allow an admin to do so manually), without accessing an access token of this user.
* For instance, if a uni hosts a Synapse server for its student clubs, one student may play different roles if member of several clubs. The nicknames in the rooms could be changed automatically to emphasize one's role in the club that corresponds to this room.

**Why it should be easily added:**

The feature _exists_, it's just about allowing a server admin to change _other people_'s nicknames in rooms.
* Indeed, a user can change their _own_ nickname in a room using `/myroomnick` on Element. Likewise for the global nickname using `/nick`.
* An admin can already change a user's _global_ nickname (there are even two ways, see below). The thing I'm asking for is analogous to it (thus the code should be analogous as well !).
* If an admin is allowed to get a user's access token, then the thing I'm asking works, using `PUT /_matrix/client/v3/rooms/<roomId>/state/m.room.member/<userId>` with a field `"displayname"` in the request json. However, we should avoid getting an access token for the users' accounts.

**Current Contradictions:**

* Although changing a user's _global_ nickname should require more authorization than _only in a room_, the converse occurs in practice, since the latter currently requires an access token for the user.
* There is zero endpoint to do what I'm asking, whereas an admin can change the global nickname of a user... using any of these _two_ endpoint that have an _identical_ behavior, namely:
    * `PUT /_matrix/client/v3/profile/<userId>/displayname`
    * `PUT /_synapse/admin/v2/users/<userId>`
Both with a field `"displayname"` in the request json.

**Comment by reivilibre** [comment]
The problem is that if we add an admin API command for everything you can do on the CS-API, this quickly gets out of hand :-)

You can use the 'Login as a User' API to get an access token (ideally use the `valid_until_ms` field so it expires), do the name change using the normal API and then log out the access token again.

- https://element-hq.github.io/synapse/latest/admin_api/user_admin_api.html#login-as-a-user

Although this takes more steps (which could be scripted away), this is functionally the same.

**Comment by anoadragon453** [comment]
Thanks for filing an issue. As @reivilibre says, this is already possible with a combination of the Synapse Admin and Client-Server APIs; just not in a single call. Adding a single API for this seems redundant.

Please open a new issue if that doesn't work for your use case. Thanks!
