### ISSUE TITLE
Client account password stolen

### ISSUE THREAD

**Issue by niudin** [element-hq/synapse#17072]
Please don't file github issues asking for support.

Instead, please join [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org)
(from a matrix.org account if necessary), and ask there.

The client account password has been stolen. I have set a strong password, but it is still stolen. Are there any security measures for client login, such as turning on MFA or IP whitelist restrictions?

**Comment by reivilibre** [comment]
Please don't file github issues asking for support.

Instead, please join [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org)
(from a matrix.org account if necessary), and ask there.
