### ISSUE TITLE
Problem with federation (401 unauthorized)

### ISSUE THREAD

**Issue by Froggy232** [element-hq/synapse#17102]
Hi,
First, sorry for using github to ask for help, I just think it's a way better forms of solving issue than matrix but if you want I will go ask help here.
I deeply want to use synapse but I have trouble with settings federation. The logs tell me : https://privatebin.alrhome.net/?9493e6d872e96b1f#3WiTo89V38wG2Kz3GyKN1mWTf2U9Z8RgMCqroHTCuKSh
 
I think there is a problem with my reverse proxy, but I don't achieve to see where. My nginx conf file is here : https://privatebin.alrhome.net/?0b68394dd33f49a9#3rUqp8pLLnxSCkNGFkjhhzGy761ozW2F4osGcL4aqkM9

Finally, my `synapse.container` file is here : https://privatebin.alrhome.net/?812a5270670e3383#4n4KiiQXxssBPXKGtxUwBrfHdMBTRJhYmbrfoFQ4Jzsg

Thanks you a lot for your help, and for your wholesome software.
Regards

**Comment by 9p4** [comment]
Does your server pass the [federation tester](https://federationtester.matrix.org)

**Comment by Froggy232** [comment]
Hi,
Thanks for the answer, so sorry for the long reply.
No, it doesn't pass the federation tester, it tell me that : 
`Get "https://82.67.85.247:8448/_matrix/key/v2/server": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

The full json log is here : https://federationtester.matrix.org/api/report?server_name=synapse.alrhome.net

Do I need to open the port 8448 in my router?
Thanks for your help!

**Comment by 9p4** [comment]
If delegation is not set up (the default), Synapse needs port 8448 to be publicly available. As your pastes are no longer accessible, I can not tell if this is the actual problem. Could you please reupload them as an attachment to the issue?

**Comment by Froggy232** [comment]
Sorry, everything works now, I just hadn't open the ports in my router.
Thanks you a lot for your help, and for your work on the software!
