### ISSUE TITLE
create the room interface setting is is_direct to true, but the result is not a people group，it is still a rooms group

### ISSUE THREAD

**Issue by yangjl114** [element-hq/synapse#17168]
### Description

Our back-end service calls the interface that creates the room /_matrix/client/r0/createRoom，We want to create a contact group，But it always turned out to be a group chat。We set the parameter is direct to true，preset is private_chat，invite is [userId]

### Steps to reproduce

call  /_matrix/client/r0/createRoom  the parameter is direct to true，preset is private_chat，invite is [userId]
result Create a group chat

### Homeserver

https://m.tjfydi.com/

### Synapse Version

1.103.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL signal  main no no 

### Workers

Single process

### Platform

aws-ec2 /ubuntu 22.04.4 LTS 22.04 jammy
synapse  docker
docker 26.0.0运行

### Relevant log output

```shell
.
```

**Comment by reivilibre** [comment]
See https://spec.matrix.org/v1.10/client-server-api/#client-behaviour-21 : you need to update the account data for your own user to mark the room as direct.

The `is_direct` flag on `/createRoom` only affects the direct flag on the invitations that are sent. When these invitations are received by someone and then accepted, their client will update their account data to mark the room as direct on their side.
