### ISSUE TITLE
Running Synapse on StartOS.  Element won't recognize Homeserver address.

### ISSUE THREAD

**Issue by caracasmc** [element-hq/synapse#17173]
Hello.  I'm running Synapse 1.98.0 on a Start9 Server Pure with StartOS.  I've completed the initial config where I have logged in as admin and created a new user ID and password apart from the admin ID.  The instructions tell me that the next step is to download Element (which I have), install it, and Sign In by clicking the Edit button next to matrix.org and entering my homeserver address.  The Homeserver address that is listed under "Interfaces" in the Synapse app on my Server Pure is a TOR address that starts with http:// then a long string of characters and ending in .onion.  There is also a LAN address field beneath it but it says, "N/A".

When I attempt to use the TOR address as the homeserver address in Element, it gives me the following error:

"Homeserver URL does not appear to be a valid matrix homeserver"

What am I doing wrong?  The Tor address is literally what is listed beneath Homeserver Address in Synapse. Why isn't it recognized?

**Comment by reivilibre** [comment]
Do you have Tor connectivity on the device that is running Element and wants to connect to the homeserver at `http://<...>.onion`?
My first suspicion here is that it's not able to connect. It is likely making a request like `http://<...>.onion/_matrix/client/v3/login` but failing. (When you do this, you should get a response like `{"flows":[{"type":"m.login.password"},{"type":"m.login.application_service"}]}`.)

What device are you trying to connect from; desktop, mobile?
