### ISSUE TITLE
PUT `/state` is rate limited against spec

### ISSUE THREAD

**Issue by ajbura** [element-hq/synapse#17188]
### Description

sending many state event by client results in getting rate limited by server. This breaks the client experience when adding existing rooms in space or re-ordering space children. 

Spec https://spec.matrix.org/v1.9/client-server-api/#put_matrixclientv3roomsroomidstateeventtypestatekey says that this endpoint is not rate limited.

### Steps to reproduce

- create a space
- open add existing room panel (cinny, or element if it has this feature)
- select 20+ rooms to add
- open browser dev tool network panel
- press add button
- results in some room not added in space their request are rate limited

### Homeserver

matrix.org

### Synapse Version

1.107.0rc1 (b=matrix-org-hotfixes,cef3519e96)

### Installation Method

Docker (matrixdotorg/synapse)

### Database

NIL

### Workers

Single process

### Platform

NIL

### Relevant log output

```shell
rate limited requests response

status code: 429
errcode: M_LIMIT_EXCEEDED
error: Too Many Requests
```

### Anything else that would be useful to know?

NIL

**Comment by erikjohnston** [comment]
Hi, the spec only has a recommendation of whether or not an endpoint is ratelimited, and in general defaults to "no" for all endpoints. This is a large source of confusion, as servers *have* to be able to ratelimit endpoints as they see fit (to mitigate abuse). c.f. https://github.com/matrix-org/matrix-spec/issues/584 for a spec issue on this.

We've seen people try and abuse `/state/` etc in the wild, so we're not going to remove the ratelimiting.
