### ISSUE TITLE
SHA2 is crackable. Request that other forms of encryption be implemented.

### ISSUE THREAD

**Issue by Daburnell112** [element-hq/synapse#17258]
So, I have a hunch the current encryption you're using isn't secure.

![image](https://github.com/element-hq/synapse/assets/8177634/5b4db7ed-2074-4703-8ba7-3081c12c8b10)

Is there a way to support other forms of encryption? Such as something more quantum resistant?

**Comment by richvdh** [comment]
Also: where is that quote from?

**Comment by xylobol** [comment]
It appears to have been generated by Copilot, judging by the font and the citation marker.

**Comment by richvdh** [comment]
Yeah, I think there's a lot of confusion here.
