### ISSUE TITLE
Document the rc_invite per_issuer default values

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/synapse#17299]
(reporting this with my Nordeck hat on)

### Description

https://github.com/element-hq/synapse/blob/f1c4dfb08b530f2bfaf9c6723ce69ccd231a3370/docs/usage/configuration/config_documentation.md?plain=1#L1761-L1763

### Steps to reproduce

see docs

### Homeserver

docs

### Synapse Version

1.108.0

### Installation Method

Other (please mention below)

### Database

no

### Workers

I don't know

### Platform

http

### Relevant log output

```shell
aaaaaaaaaaaa
```

**Comment by HarHarLinks** [comment]
https://github.com/element-hq/synapse/blob/3aae60f17b97078b2fd4bde64be063f9d34c6352/synapse/config/ratelimiting.py#L206

**Comment by devonh** [comment]
Thanks for raising this. See this PR for further tracking: https://github.com/element-hq/synapse/pull/17347
