### ISSUE TITLE
Synapse still responds to /_matrix/key/v2/server/{keyId}

### ISSUE THREAD

**Issue by Johennes** [element-hq/synapse#17323]
The `/{keyId}` parameter has been [removed](https://github.com/matrix-org/matrix-spec/pull/1350) in Matrix v1.6. This version of the specification also included [another change](https://github.com/matrix-org/matrix-spec/pull/1347) that mandates a 404 response for requests to unsupported endpoints:

> If a request for an unsupported (or unknown) endpoint is received then the server must respond with a 404 M_UNRECOGNIZED error.

However, Synapse appears to still respond to requests with `/{keyId}` as if the path component was missing. See e.g. https://matrix-federation.matrix.org/_matrix/key/v2/server/foo which returns the same 200 response as https://matrix-federation.matrix.org/_matrix/key/v2/server rather than a 404.

I assume this might actually be intentional because [until late 2022](https://github.com/matrix-org/synapse/pull/14525) Synapse itself specified the parameter on outgoing requests. However, given that this isn't part of the spec anymore I'm curious what the migration path is here, if any?

For context: I'm poking at this with my gematik hat on as we're trying to expose and prevent compatibility problems within the gematik ecosystem. The latter is currently on Matrix v1.3 but once we update our specification we'll _also_ have v1.10 implementations in the same federation.

**Comment by clokep** [comment]
> I assume this might actually be intentional 

It was intentional, there was no way to be compliant with both the new spec and old spec. Would need to dig back through blame to find the conversation about it.

**Comment by Johennes** [comment]
Ok, I see. There's probably no concrete plan to ditch support for the old spec then, or is there?

**Comment by devonh** [comment]
For reference: the conversation about this issue happened here: https://github.com/matrix-org/synapse/issues/15089#issuecomment-1522309666

As far as I'm aware, there is no concrete plan to stop supporting the old spec at this time.

The team can take a look at this & consider what the plan should be.

**Comment by Johennes** [comment]
Thanks a lot both! I think we can close this then.

**Comment by devonh** [comment]
Update: The team took a look and the plan is to continue supporting the endpoint until it is fully removed from the spec.
So I wouldn't expect support to be removed any time soon.
