### ISSUE TITLE
request: add 2FA 

### ISSUE THREAD

**Issue by Ahwxorg** [element-hq/synapse#17459]
**Description:**

I think it'd be a good idea to implement 2FA into Synapse and Element as a 2nd way to verify that it is really you. I know it is already suggested here: https://github.com/matrix-org/matrix-spec-proposals/pull/1998, but  I wanted to ask if there's any progress.

**Comment by devonh** [comment]
The current plan for user authentication in matrix is to add OIDC support via the [matrix-authentication-service](https://github.com/matrix-org/matrix-authentication-service) which implements [MSC3861](https://github.com/matrix-org/matrix-spec-proposals/pull/3861). Work on standalone 2FA is not currently planned in Synapse.
