### ISSUE TITLE
New anonymous rooms are added

### ISSUE THREAD

**Issue by honestyallan** [element-hq/synapse#17516]
New anonymous rooms are added. Users in anonymous rooms will have their user IDs displayed anonymously.

**Comment by anoadragon453** [comment]
Such a feature would require a (major) change to the Matrix protocol. Please take this up in an issue in [matrix-spec](https://github.com/matrix-org/matrix-spec) first, or [write a Matrix Spec Change proposal](https://github.com/matrix-org/matrix-spec-proposals/#matrix-specification-proposals).

Once a suitable technical proposal, we are happy to evaluate an experimental implementation.
