### ISSUE TITLE
more tutorial videos :)

### ISSUE THREAD

**Issue by xandersalarie** [element-hq/synapse#17533]
**a few instructional videos for the vidual learners with us:**

heya, during my time setting up matrix synapse in docker i found that most video guides will tell you different things. therefore i think it would be good to have a few instructional videos (e.g "setting up matrix-synapse"). i could see it becoming easier when the official company makes a dedicated video. not going into detail of what synapse is/does. but more like "how to set up synapse in docker" or a video on how to configure nginx for synapse (this would've helped me the most).

setting it up was actually quite easy. but i had to start scouring different yt videos all at once. i finally managed to set it up and unfortunately. due to corruption in my home lab, i had to set it up again (but it was way faster this time.)

maybe it would also be great if there were videos of how to set up hookshot (although that would be a job for the creator of the application).

hope this feature request finds you well.

`TLDR:`  

> official instruction videos for the visual learner would be appreciated :)

thanks for making such an amazing platform!❤️

**Comment by anoadragon453** [comment]
Hi @xandersalarie, there's a playlist here with various videos if that's helpful: https://www.youtube.com/playlist?list=PLl5dnxRMP1hWnFJYiXL3ot1NWufOqzSNX

A better venue to discuss this is on Matrix itself; either in [#synapse-admins:matrix.org](https://matrix.to/#/#synapse-admins:matrix.org) or [#synapse-dev:matrix.org](https://matrix.to/#/#synapse-dev:matrix.org). Feel free to do so if the above playlist doesn't cover your needs!

Going to close this issue in the meantime, cheers.
