### ISSUE TITLE
Clarify the support for Sliding Sync in Synapse and its compatibility with the syncv3 proxy

### ISSUE THREAD

**Issue by 4nd3r** [element-hq/synapse#17572]
Since Synapse v1.112 several Sliding Sync related changes have been merged.

The only comment I found regarding the Sliding Sync in Synapse versus the syncv3 proxy was [here](https://github.com/element-hq/synapse/pull/17187#pullrequestreview-2159272522).

It now appears (#17571) that this feature is becoming switchable and Synapse will publish this capability as well.

Could you please clarify, in documentation and/or release notes, how this affects installations that use the syncv3 proxy?

Should I disable the proxy, remove related bit in `.well-known/matrix/client` and enable Sliding Sync directly in Synapse now?

How this impacts Element-X clients/users?

**Comment by erikjohnston** [comment]
Hi @4nd3r, we're currently in the middle of adding sliding sync support to Synapse, but it's not yet ready for people to start switching over (though hopefully will be soon). Once we get to the stage where people can start using the native implementation we'll shout about it and provide docs.

**Comment by Shahroz16** [comment]
@erikjohnston thanks much for the update, in the meantime, are they any docs available for people who want to try out sliding sync without the proxy server? just to get it working?
