### ISSUE TITLE
Separate freezing unauth media endpoints and enabling auth media into two separate settings

### ISSUE THREAD

**Issue by BurnyBoi** [element-hq/synapse#17639]
**Description:**

Currently there is [one setting](https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#enable_authenticated_media) that when enabled both requires authentication on the new media endpoints, AND freezes media on the legacy unauthenticated endpoints. My plan was to enable auth media, and then implement nginx rules to lock down the unauthed endpoint to a small subset of users, but with both of these actions on the same setting I can't do this.

Requesting that authenticated media is split into two separate config options: One for requiring auth on the new endpoints, and another for freezing the old endpoints.

**Comment by tulir** [comment]
The new endpoints are always enabled and always require auth, there's no option to not require auth nor to disable them.

`enable_authenticated_media` simply prevents new media from being accessible over old endpoints, as the docs say:

> When set to true, all subsequent media uploads will be marked as authenticated, and will not be available over legacy unauthenticated media endpoints
