### ISSUE TITLE
Reset federation retry timer after receiving a message from the (formerly) offline homeserver

### ISSUE THREAD

**Issue by aerusso** [element-hq/synapse#17769]
**Description:**

If homeserver `A` goes down, and a user from homeserver `B` tries to contact someone on `A`,  `B` will (correctly) notice that `A` is offline.  If `A` comes back online, `B` (as far as I can tell) will wait until its retry timer expires before attempting to contact `A` again.

However, if a user on `A` sends a message to a user on `B`, `B` becomes aware that `A` is online again.  At this point, it makes sense for `B` to start retrying sending messages to `A`.

This would significantly improve the user experience.  Until these retry timers expire, users on `B` will be able to send message to users on `A`, but not vice-versa.

**Comment by daedric7** [comment]
I was under the impression that the backoff behaviour is exactly that, it gets reset to 0 as soon as event from MIA is received.

Do you have any evidence that that's not the case ?

**Comment by aerusso** [comment]
Yes.  Quite literally the example I gave was my observation using 1.115.0. I manage two homeservers, took one down, and accidentally sent a test message to it before bringing it back up.  As an add-on to this problem, the encryption keys for some messages were never federated between the clients, leading to apparently permanently undecryptable messages on one of the clients.

That said, I have only tested this with E2E encryption.  Could that cause this to happen?  Can you point to the line that re-sends outstanding requests?

**Comment by daedric7** [comment]
Ok, a pratical test:

![image](https://github.com/user-attachments/assets/15f959d0-f473-4f5d-bfd3-dc55dcbd07fe)

My synapse believes that server is down (and it is, server failed to boot)

Server came up:

![image](https://github.com/user-attachments/assets/a532d35b-21a1-4948-9560-76c88fa9c366)

I did nothing else other than make the server boot.

**Comment by aerusso** [comment]
I can't seem to reproduce this on 1.116.  Maybe something changed since 1.115?  I'll reopen this if I can get a reproducer.

Thanks for bearing with me.
