### ISSUE TITLE
Divide thread and messages permissions

### ISSUE THREAD

**Issue by Jlucu4ka228** [element-hq/synapse#17761]
**Description:**
I'd like to be possible to grant permission to create and answer to threads separately from usual messages. I think it would be useful for some rooms that are kind of news rooms, so that people could discuss news in these threads, keeping room clean.

**Comment by or10n1** [comment]
Good idea. It'll solve my problem.

**Comment by Jlucu4ka228** [comment]
Moved to https://github.com/matrix-org/matrix-spec/issues/1953
