### ISSUE TITLE
Purge Media of banned users and moderated messages

### ISSUE THREAD

**Issue by slatian** [element-hq/synapse#17777]
**Description:**

Synapse should automatically delete media attached to messges or sent by users that have been the target of "destructive" moderation actions, both local and remote.

-- Greetings from a bunch of admins who had to purge some very yucky images (🤮)

**Comment by anoadragon453** [comment]
Hello. Yes, this is very much top-of-mind for Trust & Safety efforts in Matrix. However, changes to the Matrix spec need to happen first before this can be done. https://github.com/matrix-org/matrix-spec-proposals/pull/3911 describes this changes, and https://github.com/matrix-org/matrix-spec-proposals/pull/3916, released in the most recent Matrix spec version, was a big pre-requisite for it.

Please subscribe to https://github.com/matrix-org/matrix-spec-proposals/pull/3911 for forward progress on this issue. Once ready, we can implement the changes in Synapse and close this gap in moderation. Thanks for bearing with us.

In the meantime, you can manually quarantine media [by room](https://element-hq.github.io/synapse/latest/admin_api/media_admin_api.html#quarantining-media-in-a-room) or [by user](https://element-hq.github.io/synapse/latest/admin_api/media_admin_api.html#quarantining-all-media-of-a-user), as well as [purge media by user](https://element-hq.github.io/synapse/latest/admin_api/media_admin_api.html#delete-media-uploaded-by-a-user). You can also [delete the remote media cache](https://element-hq.github.io/synapse/latest/admin_api/media_admin_api.html#purge-remote-media-api) if the offensive media was uploaded by a user on another homeserver.
