### ISSUE TITLE
Provide packages for Ubuntu Noble (24.04) and Oracular (24.10)

### ISSUE THREAD

**Issue by richvdh** [element-hq/synapse#17811]
https://packages.matrix.org/debian/pool/main/m/matrix-synapse-py3/ does not include packages built for Noble or Oracular.

(It *does* include packages for lunar and mantic, both of which are out of support)

Previously: https://github.com/matrix-org/synapse/pull/16524

**Comment by richvdh** [comment]
Related: https://github.com/matrix-org/pkg-repo-configs/pull/25

**Comment by ajkessel** [comment]
Attempting to install the mantic build has this one conflict on Noble:
```
 matrix-synapse-py3 : Depends: libicu72 (>= 72.1~rc-1~) but it is not installable
 ```
 Hope this can be fixed soon!
