### ISSUE TITLE
Unable to Contact Homeserver - Element X (IOS)

### ISSUE THREAD

**Issue by lucamaximilianegger** [element-hq/synapse#17851]
### Description

I'm currently setting up a Matrix server, and everything seems to be running fine. I'm able to get a 200 OK response from the following URLs:

    https://matrix.dreamnetwork.space/
    https://matrix.dreamnetwork.space/_synapse/admin/v1/server_version
    https://matrix.dreamnetwork.space/.well-known/matrix/client
    https://matrix.dreamnetwork.space/_matrix/client/versions

However, when I try to log in using Element X on my iPhone 14 Pro, which is running iOS 18.0.1, I get an error saying the homeserver is unreachable. The log shows the following message:

css

2024-10-18T19:03:22.301572Z ERROR elementx: Failed configuring a server: ServerUnreachable(message: "error sending request for url (https://matrix.dreamnetwork.space/.well-known/matrix/client)") | AuthenticationService.swift:86 | spans: root

I've tried debugging the issue, but I haven't been able to resolve it. Oddly enough, when I open the URL https://matrix.dreamnetwork.space/.well-known/matrix/client in the browser on my phone, I receive a 200 OK response.

I'm running out of ideas on how to fix this and would appreciate any help in resolving the issue.

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

### Homeserver

matrix.dreamnetwork.space

### Synapse Version

v1.117.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL v14 (New Docker Container)

### Workers

Single process

### Platform

ARM, Ubuntu, Docker Compose File

### Relevant log output

```shell
2024-10-18T19:03:22.301572Z ERROR elementx: Failed configuring a server: ServerUnreachable(message: "error sending request for url (https://matrix.dreamnetwork.space/.well-known/matrix/client)") | AuthenticationService.swift:86 | spans: root
```

**Comment by daedric7** [comment]
Can you try removing that last / ??

```
curl -s https://matrix.dreamnetwork.space/.well-known/matrix/client | jq
{
  "m.homeserver": {
    "base_url": "https://matrix.dreamnetwork.space/" <-- here
  }
}

```

**Comment by lucamaximilianegger** [comment]
> https://matrix.dreamnetwork.space/.well-known/matrix/client

A funny point in the homeserver.yml is that there's no backslash. It just says:

`# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html

# The server name used for the Matrix instance. This name should be the public Fully Qualified Domain Name (FQDN).
public_baseurl: "https://matrix.dreamnetwork.space"`

**Comment by daedric7** [comment]
Wait, that .well-known is being served by synapse itself ?

**Comment by lucamaximilianegger** [comment]
> Wait, that .well-known is being served by synapse itself ?

Yea it is, it takes the configuration out of the Homeserver.yml and then publish that .well_known.

**Comment by daedric7** [comment]
You mean with this?

https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#extra_well_known_client_content

**Comment by lucamaximilianegger** [comment]
> You mean with this?
> 
> https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#extra_well_known_client_content

I just used: 

"[public_baseurl](https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#public_baseurl)

The public-facing base URL that clients use to access this Homeserver (not including _matrix/...). This is the same URL a user might enter into the 'Custom Homeserver URL' field on their client. If you use Synapse with a reverse proxy, this should be the URL to reach Synapse via the proxy. Otherwise, it should be the URL to reach Synapse's client HTTP listener (see ['listeners'](https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#listeners) below).

Defaults to https://<server_name>/.

Example configuration:

public_baseurl: https://example.com/"

This option should be everything you need to connect to your hoemserver.

**Comment by anoadragon453** [comment]
A few notes:

* I tried putting both "https://matrix.dreamnetwork.space" and "matrix.dreamnetwork.space" into my Element X **Android** client and had no issues getting to the sign in page. This makes me think it might be something specific to Element X iOS.
* Technically you don't need to specify `m.homeserver->base_url` at all as you're not delegating from one host to another. Typically one would do that by using, e.g. `dreamnetwork.space` as their configured Synapse `server_name`, and then use the client well-known file to point clients to `matrix.dreamnetwork.space` for the actual requests. But it appears that `matrix.dreamnetwork.space` is your `server_name`, and thus no delegation is needed.
    * Note that Synapse will always serve a client well-known file if the `public_baseurl` option is set. However, you don't necessary need to route to it in your reverse proxy.
* This is an issue tracker for bugs in Synapse. General support requests like this are best done in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org). I'd also recommend making an issue on the [Element X iOS issue tracker](https://github.com/element-hq/element-x-ios) for further discussion.

Closing since this is effectively a support request. But if it ends up being due to a bug in Synapse somewhere, please open a new issue and we'll take a look. Good luck!
