### ISSUE TITLE
Only allow specific users to use sliding sync

### ISSUE THREAD

**Issue by swilkicki** [element-hq/synapse#17860]
Requesting a way to lock down sliding sync to only a subset of users. In my case I just want to try sliding sync on my homeserver without allowing everyone to use it to prevent using more database storage & resources.

Currently the one workaround I can think of would be to use nginx allow/deny rules on the endpoints.

**Comment by anoadragon453** [comment]
> Currently the one workaround I can think of would be to use nginx allow/deny rules on the endpoints.

This was what I had in mind as I was reading your feature request. Any reason that isn't a suitable solution?

Note that based on internal testing, a client pulling data via sliding sync uses far *less* resources than one using legacy sync.

**Comment by swilkicki** [comment]
Thank you for the insight as well as the endpoints. I have gone with using nginx rules and this seems to be working.
