### ISSUE TITLE
MEliment

### ISSUE THREAD

**Issue by TELINGEL** [element-hq/synapse#17935]
I'm retesting Element Desktop on GNOME, one thing that can cause this is if you remove one of the many `xdg-desktop-portal-*` packages. On my desktop running XFCE I accidentally removed `xdg-desktop-portal-xapp` which was what was allowing Element Desktop to encrypt and decrypt session data.

I don't believe this was the case for my issue when using Element Desktop on GNOME but it's something more technical users that are having this issue can check.

_Originally posted by @konomikitten in https://github.com/element-hq/element-desktop/issues/692#issuecomment-2424471557_

**Comment by morguldir** [comment]
This doesn’t seem related to synapse
