### ISSUE TITLE
v1.120.1 and 1.20.2 are not showing as the latest releases

### ISSUE THREAD

**Issue by koehn** [element-hq/synapse#17990]
### Description

Usually when a new version of synapse is shipped, it is sent as a release. The two today are tagged, but do not have a GitHub release associated with them. 

Not sure if this is intentional or not. 

### Steps to reproduce

1. Go to https://github.com/element-hq/synapse/releases
2. Notice the 1.120.0 is the latest release; 1.120.1 and 1.120.2 are not listed. 
3. Go to https://github.com/element-hq/synapse/tags
4. Notice that 1.120.1 and 1.120.2 are listed. 

### Homeserver

All of them

### Synapse Version

1.120.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

all of them

### Workers

Single process

### Platform

Any/all

### Relevant log output

```shell
https://github.com/element-hq/synapse/releases
https://github.com/element-hq/synapse/tags
```

**Comment by sandhose** [comment]
There is always a delay between the version being tagged and it being published on GitHub, because we need to wait for CI to build various packages. 1.120.1 failed to publish properly, which is why we did 1.120.2 right after.
