### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by XayOn** [element-hq/synapse#2]
Migration to the new repository has been already "enforced" as per https://github.com/matrix-org/synapse/commit/e1f8440c8959719a417fbf1bdda11406cfdf523d

Wich led to docker images latest ( https://hub.docker.com/layers/matrixdotorg/synapse/latest/images/sha256-f0b0eb32dfe513c3901c9ff4fa5672723c2c0c25c38b06261a95f985a441850b?context=explore ) and development ( https://hub.docker.com/layers/matrixdotorg/synapse/develop/images/sha256-e73a72c932d69d1ca28bb959ad3a48ed58a5e3e2743adfd90fd5058006721e2c?context=explore ) being broken.

As of now, every docker user that wants to have their images up-to-date can't really do it...

**Comment by XayOn** [comment]
Parece que hay un action, pero no esta funcionando https://github.com/element-hq/synapse/actions/runs/7198436857

**Comment by denschub** [comment]
The `matrixdotorg/synapse` image on Docker Hub still works, so if you pulled `ghcr.io/matrix-org/synapse:latest` previously, you can just replace that with `matrixdotorg/synapse:latest`, and get the v1.98.0 release that actually lets you use it.

**Comment by nightah** [comment]
> The `matrixdotorg/synapse` image on Docker Hub still works, so if you pulled `ghcr.io/matrix-org/synapse:latest` previously, you can just replace that with `matrixdotorg/synapse:latest`, and get the v1.98.0 release that actually lets you use it.

I don't believe this is accurate, you sure you're using the most up-to-date `latest` tag `https://hub.docker.com/layers/matrixdotorg/synapse/latest/images/sha256-f0b0eb32dfe513c3901c9ff4fa5672723c2c0c25c38b06261a95f985a441850b?context=explore`?

The above fails with the error:

```
Starting synapse with args -m synapse.app.homeserver --config-path /data/homeserver.yaml

Synapse is no longer being developed under the matrix-org organization. See the
README.rst for more details.

Please update your git remote to pull from element-hq/synapse:

   git remote set-url origin git@github.com:element-hq/synapse.git
```

Pinning to [`v1.98.0`](https://hub.docker.com/layers/matrixdotorg/synapse/v1.98.0/images/sha256-8d962e48a1d88d2fb646c82b1babf4dd0ed765b21a4cf15600d77e90e46dc413?context=explore) works though.

**Comment by henryclw** [comment]
Will there be a github action for automatically building docker image for this repo? If so, do we need to change our docker image name to match it?

**Comment by XayOn** [comment]
> Will there be a github action for automatically building docker image for this repo? If so, do we need to change our docker image name to match it?

The action is actually there as it's been just forked. So they only need to add the secrets.

> The matrixdotorg/synapse image on Docker Hub still works, so if you pulled ghcr.io/matrix-org/synapse:latest previously, you can just replace that with matrixdotorg/synapse:latest, and get the v1.98.0 release that actually lets you use it.

Nope, as stated on this issue, it's not working, matrixdotorg/synapse:latest is broken since yesterday.

**Comment by denschub** [comment]
> Nope, as stated on this issue, it's not working, matrixdotorg/synapse:latest is broken since yesterday.

This isn't true, and I wouldn't have said what I said if I didn't successfully deploy it. The very image you referenced does not have that exit condition:

```plain
# docker run -it --entrypoint bash 'matrixdotorg/synapse@sha256:f0b0eb32dfe513c3901c9ff4fa5672723c2c0c25c38b06261a95f985a441850b'

root@c66498567f63:/# grep "# Update your remotes folks." /usr/local/lib/python3.11/site-packages/synapse/__init__.py | wc -l
0
```

and neither does the `1d4ec5a96819e5c7b1c4525bd7f4411b768b62ccb5ca07e19aa9e88b61c91750` that has been pushed just now. Looks like they manually pushed a new `latest` to DockerHub.

`ghcr.io/matrix-org/synapse:latest` still is at `sha256:6ac3bba2c511117c3367451ee814842b9399a83f9821e05978ff7f2eb28c9e4d `, which was the original image that has been pushed to DockerHub as well, and that one *is* broken:

```plain
# docker run -it --entrypoint bash 'matrixdotorg/synapse@sha256:6ac3bba2c511117c3367451ee814842b9399a83f9821e05978ff7f2eb28c9e4d'

root@6a03d5b237f8:/# grep "# Update your remotes folks." /usr/local/lib/python3.11/site-packages/synapse/__init__.py | wc -l
1
```

and, of course, the GitHub Container Registry image will stay broken since the repo is archived now.

Although, seeing them pushing new images manually probably means that force-pinning a known-working image is a smarter move here.

**Comment by XayOn** [comment]
> and neither does the 1d4ec5a96819e5c7b1c4525bd7f4411b768b62ccb5ca07e19aa9e88b61c91750 that has been pushed just now. Looks like they manually pushed a new latest to DockerHub.

So... It's been fixed by now. That's cool (altough, it's a little worrysome that it's been done silently). 

When I reported it, the :latest image was broken on DH 

```
matrixdotorg/synapse                latest    sha256:20ae0f66ec14953b2cb54ae9ad3c5b85baa3021f7a9c33c73ecf5dda5d76bebe   23 hours ago    439MB
```

```
docker run -it --entrypoint bash 'matrixdotorg/synapse:latest'
root@dba782cab8d6:/# grep "# Update your remotes folks." /usr/local/lib/python3.11/site-packages/synapse/__init__.py
# Update your remotes folks.
```

I might be a little paranoid, but I wouldn't dare use that one, I can't find it on the CI, I agree that it seems to have been manually pushed...

I'd argue to keep this issue open until they have the new CI set up, so people can be informed.

**Comment by XayOn** [comment]
A little communication would have been cool too...

**Comment by denschub** [comment]
> When I reported it, the :latest image was broken on DH

Ah, yeah, that's a different hash... :/ I agree that it's super confusing, and very frustrating.

**Comment by erikjohnston** [comment]
Hi all,

Firstly: we're *really sorry* that we messed up and broke the docker images, that was entirely unintentional on our part. We were aiming to make this as seamless as possible for people using packages. 

Hopefully both docker hub and gchr.io have working images for `:latest` now. I've also copied over `v1.98.0` and tagged it as `latest` on ghcr.io/element-hq/synapse, so people can start using the new ghcr.io location.

Going forwards I mean to try and change our CI to ensure that `:latest` points at the latest tagged version, rather than whatever is on the `master` branch. 

Please do shout if people have any further problems with docker images.

**Comment by XayOn** [comment]
> Firstly: we're really sorry that we messed up and broke the docker images, that was entirely unintentional on our part. We were aiming to make this as seamless as possible for people using packages.

Thanks, this clarification is definitely the way to go.

> Hopefully both docker hub and gchr.io have working images for :latest now. I've also copied over v1.98.0 and tagged it as latest on ghcr.io/element-hq/synapse, so people can start using the new ghcr.io location.

That makes it so it's trazable to the CI runs too, wich is perfect!

> Going forwards I mean to try and change our CI to ensure that :latest points at the latest tagged version, rather than whatever is on the master branch.

This is a great idea. Will be a nice compromise to those who want to still be on the latest release, and, if we want to keep on bleeding edge and test things out, there's the development image (wich I hope will still be kept)

**Comment by Helvio88** [comment]
> Hi all,
> 
> Firstly: we're _really sorry_ that we messed up and broke the docker images, that was entirely unintentional on our part. We were aiming to make this as seamless as possible for people using packages.
> 
> Hopefully both docker hub and gchr.io have working images for `:latest` now. I've also copied over `v1.98.0` and tagged it as `latest` on ghcr.io/element-hq/synapse, so people can start using the new ghcr.io location.
> 
> Going forwards I mean to try and change our CI to ensure that `:latest` points at the latest tagged version, rather than whatever is on the `master` branch.
> 
> Please do shout if people have any further problems with docker images.

Thank you for the clarification! I believe I'm not alone when I say you do not need to apologize. It's a huge change and things happen. I'm very thankful for your dedication to this amazing project (and again I don't believe I'm alone in it)!

Also:
`ghcr.io/element-hq/synapse:latest` is now up and running here, just wanted to let everyone know!

**Comment by YamatoRyou** [comment]
> Hi all,
> 
> Firstly: we're _really sorry_ that we messed up and broke the docker images, that was entirely unintentional on our part. We were aiming to make this as seamless as possible for people using packages.
> 
> Hopefully both docker hub and gchr.io have working images for `:latest` now. I've also copied over `v1.98.0` and tagged it as `latest` on ghcr.io/element-hq/synapse, so people can start using the new ghcr.io location.
> 
> Going forwards I mean to try and change our CI to ensure that `:latest` points at the latest tagged version, rather than whatever is on the `master` branch.
> 
> Please do shout if people have any further problems with docker images.

So after switching branches, the new version of the image is no longer uploaded to Docker Hub?
Due to some force majeure, ghcr.io is very slow in my place, but Docker Hub is not.
